In [20]:
import numpy as np


In [21]:
RI = np.array([0,0,0.58,0.90,1.12,1.24,1.32,1.41,1.45,1.49,1.51,1.48,1.56,1.57,1.58])

mainarr = np.array([[1   ,2   ,2   ,3   ,4   ,5   ,5   ,6   ,7   ,8   ,8],
                   [1/2 ,1   ,2   ,3   ,3   ,4   ,5   ,6   ,7   ,8   ,8],
                   [1/2 ,1/2 ,1   ,2   ,3   ,4   ,4   ,5   ,6   ,7   ,7],
                   [1/3 ,1/3 ,1/2 ,1   ,2   ,3   ,3   ,4   ,5   ,7   ,8],
                   [1/4 ,1/3 ,1/3 ,1/2 ,1   ,2   ,2   ,3   ,4   ,5   ,6],
                   [1/5 ,1/4 ,1/4 ,1/3 ,1/2 ,1   ,2   ,4   ,5   ,7   ,7],
                   [1/5 ,1/5 ,1/4 ,1/3 ,1/2 ,1/2 ,1   ,2   ,3   ,5   ,6],
                   [1/6 ,1/6 ,1/5 ,1/4 ,1/3 ,1/4 ,1/2 ,1   ,2   ,4   ,5],
                   [1/7 ,1/7 ,1/6 ,1/5 ,1/4 ,1/5 ,1/3 ,1/2 ,1   ,3   ,4],
                   [1/8 ,1/8 ,1/7 ,1/7 ,1/5 ,1/7 ,1/5 ,1/4 ,1/3 ,1   ,3],
                   [1/8 ,1/8 ,1/7 ,1/8 ,1/6 ,1/7 ,1/6 ,1/5 ,1/4 ,1/3 ,1]]
                  )

n = mainarr[0].size

In [22]:
float_formatter = "{:.4f}".format
np.set_printoptions(formatter={'float_kind':float_formatter})

In [23]:
colsum = mainarr.sum(axis=0)
print(colsum)

[3.5429 5.1762 6.9857 10.8845 14.9500 20.2357 23.2000 31.9500 40.5833
 55.3333 63.0000]


In [24]:
i=0
normalizedform = np.array(mainarr)
for p in mainarr:
    normalizedform[i] = np.divide(mainarr[i] , colsum)
    i+=1
    
print(normalizedform)



[[0.2823 0.3864 0.2863 0.2756 0.2676 0.2471 0.2155 0.1878 0.1725 0.1446
  0.1270]
 [0.1411 0.1932 0.2863 0.2756 0.2007 0.1977 0.2155 0.1878 0.1725 0.1446
  0.1270]
 [0.1411 0.0966 0.1431 0.1837 0.2007 0.1977 0.1724 0.1565 0.1478 0.1265
  0.1111]
 [0.0941 0.0644 0.0716 0.0919 0.1338 0.1483 0.1293 0.1252 0.1232 0.1265
  0.1270]
 [0.0706 0.0644 0.0477 0.0459 0.0669 0.0988 0.0862 0.0939 0.0986 0.0904
  0.0952]
 [0.0565 0.0483 0.0358 0.0306 0.0334 0.0494 0.0862 0.1252 0.1232 0.1265
  0.1111]
 [0.0565 0.0386 0.0358 0.0306 0.0334 0.0247 0.0431 0.0626 0.0739 0.0904
  0.0952]
 [0.0470 0.0322 0.0286 0.0230 0.0223 0.0124 0.0216 0.0313 0.0493 0.0723
  0.0794]
 [0.0403 0.0276 0.0239 0.0184 0.0167 0.0099 0.0144 0.0156 0.0246 0.0542
  0.0635]
 [0.0353 0.0241 0.0204 0.0131 0.0134 0.0071 0.0086 0.0078 0.0082 0.0181
  0.0476]
 [0.0353 0.0241 0.0204 0.0115 0.0111 0.0071 0.0072 0.0063 0.0062 0.0060
  0.0159]]


In [25]:
criteriaweights = normalizedform.sum(axis=1)/n
print(criteriaweights)

[0.2357 0.1947 0.1525 0.1123 0.0781 0.0751 0.0532 0.0381 0.0281 0.0185
 0.0137]


In [26]:
#data consistency checling started

i=0
c1 = np.array(mainarr)
for p in mainarr:
    c1[i] = np.multiply(mainarr[i] , criteriaweights)
    i=i+1

print(c1)



[[0.2357 0.3894 0.3050 0.3369 0.3122 0.3756 0.2659 0.2287 0.1967 0.1482
  0.1099]
 [0.1178 0.1947 0.3050 0.3369 0.2342 0.3005 0.2659 0.2287 0.1967 0.1482
  0.1099]
 [0.1178 0.0974 0.1525 0.2246 0.2342 0.3005 0.2127 0.1906 0.1686 0.1297
  0.0961]
 [0.0786 0.0649 0.0762 0.1123 0.1561 0.2253 0.1595 0.1525 0.1405 0.1297
  0.1099]
 [0.0589 0.0649 0.0508 0.0561 0.0781 0.1502 0.1063 0.1143 0.1124 0.0926
  0.0824]
 [0.0471 0.0487 0.0381 0.0374 0.0390 0.0751 0.1063 0.1525 0.1405 0.1297
  0.0961]
 [0.0471 0.0389 0.0381 0.0374 0.0390 0.0376 0.0532 0.0762 0.0843 0.0926
  0.0824]
 [0.0393 0.0325 0.0305 0.0281 0.0260 0.0188 0.0266 0.0381 0.0562 0.0741
  0.0687]
 [0.0337 0.0278 0.0254 0.0225 0.0195 0.0150 0.0177 0.0191 0.0281 0.0556
  0.0549]
 [0.0295 0.0243 0.0218 0.0160 0.0156 0.0107 0.0106 0.0095 0.0094 0.0185
  0.0412]
 [0.0295 0.0243 0.0218 0.0140 0.0130 0.0107 0.0089 0.0076 0.0070 0.0062
  0.0137]]


In [27]:
weightedsum = c1.sum(axis=1)

#weightedsum upon criteria weight
naipata = np.divide(weightedsum,criteriaweights)
print(naipata)

[12.3218 12.5223 12.6215 12.5170 12.3915 12.1237 11.7915 11.5118 11.3618
 11.1853 11.4155]


In [28]:
lamda = naipata.sum(axis=0)/n

lamda=round(lamda, 4) 
print(lamda)

11.9785


In [29]:
#now we find consistency index CI

CI = (lamda-n)/(n-1)
CI = round(CI,5)
print(CI)


0.09785


In [30]:
#cr is consistency ratio = consistency index upon random index
CR = CI / RI[n-1]

print(CR)


0.06480132450331126


In [31]:
if(CR<0.10):
    print("VALUES ARE CONSISTENT - go ahead")
else:
    print("criteria weights are not consistent reEnter the values")
    

VALUES ARE CONSISTENT - go ahead


In [32]:
#function made

def bene(arr) :
    max1 = np.max(arr[1])
    max2 = np.max(arr[2])
    max3 = np.max(arr[3])

    ite=0
    for i in arr[1] :
        arr[1][ite]=i/max1
        ite+=1
    ite=0
    for i in arr[2] :
        arr[2][ite]=i/max2
        ite+=1
    
    ite=0
    for i in arr[3] :
        arr[3][ite]=i/max3
        ite+=1
        
    #non beneficial min/i
    ite=0
    min1 = np.min(arr[0])
    for i in arr[0] :
        arr[0][ite]=min1/i
        ite=ite+1


In [33]:
#Tla transpose list array   ctla copy of tla
listarray = np.array([[250,16,12,5],[200,16,8,3],[300,32,16,4],[275,32,8,4],[225,16,16,2]])
print("\n")
Tla = listarray.T
Tla = Tla.astype('float64') 


# function called
bene(Tla)
Tla = Tla.T
print(Tla)





[[0.8000 0.5000 0.7500 1.0000]
 [1.0000 0.5000 0.5000 0.6000]
 [0.6667 1.0000 1.0000 0.8000]
 [0.7273 1.0000 0.5000 0.8000]
 [0.8889 0.5000 1.0000 0.4000]]


In [34]:
cw = 0
for i in Tla:
    Tla[cw] = np.multiply(Tla[cw],criteriaweights)
    cw+=1
print(Tla)


ValueError: operands could not be broadcast together with shapes (4,) (11,) 

In [ ]:
#weighted normalized decision matrix

# out_arr = np.multiply(in_arr1, in_arr2) ye galat hai for what i am doin     

# out_arr=np.array(in_arr1)*np.array(in_arr2) this is right

# wndm = np.array(Tla)*np.array(cw)
# print(wndm)
#now this is according to the other video example


In [ ]:
perfscore = Tla.sum(axis=1)
print (perfscore)

In [ ]:
rankArr = np.array(perfscore)
ranks = perfscore.size
for score in rankArr :
    rankArr[rankArr.argmin()]=ranks
    ranks-=1
print(rankArr)

In [ ]:
finalarr = np.column_stack([listarray,rankArr])
print(finalarr)

In [ ]:
finalarr = finalarr[finalarr[:,finalarr[0].size-1].argsort()]
print(finalarr)