In [13]:
import numpy as np
import pandas as pd
RI = np.array([0,0,0.58,0.90,1.12,1.24,1.32,1.41,1.45,1.49,1.51,1.48,1.56,1.57,1.58])

In [14]:
df =pd.read_csv("WesternGhatData/1Elevation.csv")
elevation= df.to_numpy()

df =pd.read_csv("WesternGhatData/2Slope.csv")
slope= df.to_numpy()

df =pd.read_csv("WesternGhatData/3DistancefromRiver.csv")
river= df.to_numpy()

df =pd.read_csv("WesternGhatData/4Drainage.csv")
drainage= df.to_numpy()

df =pd.read_csv("WesternGhatData/5FlowAccumulation.csv")
flow= df.to_numpy()

df =pd.read_csv("WesternGhatData/6TWI.csv")
twi= df.to_numpy()

df =pd.read_csv("WesternGhatData/7Rainfall.csv")
rainfall= df.to_numpy()

df =pd.read_csv("WesternGhatData/8Landuse.csv")
landuse= df.to_numpy()

df =pd.read_csv("WesternGhatData/9SoilTexture.csv")
soil= df.to_numpy()

df =pd.read_csv("WesternGhatData/10TRI.csv")
tri= df.to_numpy()

df =pd.read_csv("WesternGhatData/11Geology.csv")
geology= df.to_numpy()



In [15]:
data = np.array([[1   ,2   ,2   ,3   ,4   ,5   ,5   ,6   ,7   ,8   ,8],
                   [1/2 ,1   ,2   ,3   ,3   ,4   ,5   ,6   ,7   ,8   ,8],
                   [1/2 ,1/2 ,1   ,2   ,3   ,4   ,4   ,5   ,6   ,7   ,7],
                   [1/3 ,1/3 ,1/2 ,1   ,2   ,3   ,3   ,4   ,5   ,7   ,8],
                   [1/4 ,1/3 ,1/3 ,1/2 ,1   ,2   ,2   ,3   ,4   ,5   ,6],
                   [1/5 ,1/4 ,1/4 ,1/3 ,1/2 ,1   ,2   ,4   ,5   ,7   ,7],
                   [1/5 ,1/5 ,1/4 ,1/3 ,1/2 ,1/2 ,1   ,2   ,3   ,5   ,6],
                   [1/6 ,1/6 ,1/5 ,1/4 ,1/3 ,1/4 ,1/2 ,1   ,2   ,4   ,5],
                   [1/7 ,1/7 ,1/6 ,1/5 ,1/4 ,1/5 ,1/3 ,1/2 ,1   ,3   ,4],
                   [1/8 ,1/8 ,1/7 ,1/7 ,1/5 ,1/7 ,1/5 ,1/4 ,1/3 ,1   ,3],
                   [1/8 ,1/8 ,1/7 ,1/8 ,1/6 ,1/7 ,1/6 ,1/5 ,1/4 ,1/3 ,1]]
                  )

data = np.array([[1, 3 , 1/2],
                 [1/3 , 1,3 ],
                 [2  , 1/3 , 1]])

n = data[0].size

float_formatter = "{:.3f}".format
np.set_printoptions(formatter={'float_kind':float_formatter})

In [16]:
#converts normal into fuzzyarray
def fuzzify(data):
    n = data[0].size
    mainarr = np.full((n,n,3),0,dtype=float)
    for i in range(0,n):
        for j in range(0,n):
            if (data[i][j]>=1):
                mainarr[i][j][0]= data[i][j] if(data[i][j]==1 or data[i][j]==9) else data[i][j]-1
                mainarr[i][j][2]= data[i][j] if(data[i][j]==1 or data[i][j]==9) else data[i][j]+1
            else:
                for k in range(2,10):
                    if (1/k==data[i][j]):
                        mainarr[i][j][0]= data[i][j] if(data[i][j]==9) else 1/(k+1)
                        mainarr[i][j][2]= data[i][j] if(data[i][j]==9) else 1/(k-1)
            mainarr[i][j][1]= data[i][j]
    return mainarr

In [17]:
mainarr = fuzzify(data)
geoMean = mainarr.sum(axis=1)
fuzzyWeight=np.full((n,3),0,dtype=float)
for i in range(0,n):
    fuzzyWeight[i] = np.multiply(geoMean[i] , np.reciprocal(np.flip(geoMean.sum(axis=0),0)))
print(fuzzyWeight) 

[[0.208 0.370 0.679]
 [0.203 0.356 0.623]
 [0.141 0.274 0.509]]


In [18]:
V =np.full((n,n),0,dtype=float)

# arr=fuzzyWeight.copy()

for i in range(0,n):
    arr1 = fuzzyWeight[i]
   
    for j in range(0,n):
        arr2=fuzzyWeight[j]
        if(i==j):
            V[i][j]=2
        elif arr1[1]>=arr2[1]:
            V[i][j]=1
        elif arr2[0]>=arr1[2]:
            V[i][j]=0
        else:
            V[i][j]=(arr2[0]-arr1[2])/((arr1[1]-arr1[2])-(arr2[1]-arr2[0]))
print(V)

[[2.000 1.000 1.000]
 [0.968 2.000 1.000]
 [0.758 0.788 2.000]]


In [19]:


nonFuzzyWeights = np.divide(V.min(axis=1),V.min(axis=1).sum(axis=0))
print(nonFuzzyWeights)


[0.367 0.355 0.278]
