In [87]:
import numpy as np


In [88]:
RI = np.array([0,0,0.58,0.90,1.12,1.24,1.32,1.41,1.45,1.49])

mainarr = np.array([[1 , 5  ,4   ,7],
                   [1/5, 1  ,1/2 ,3],
                   [1/4, 2  ,1   ,3],
                   [1/7, 1/3,1/3 ,1]])

n = mainarr[0].size

In [89]:
float_formatter = "{:.4f}".format
np.set_printoptions(formatter={'float_kind':float_formatter})

In [90]:
colsum = mainarr.sum(axis=0)
print(colsum)

[1.5929 8.3333 5.8333 14.0000]


In [92]:
i=0
normalizedform = np.array(mainarr)
for p in mainarr:
    normalizedform[i] = np.divide(mainarr[i] , colsum)
    i+=1
    
print(normalizedform)



[[0.6278 0.6000 0.6857 0.5000]
 [0.1256 0.1200 0.0857 0.2143]
 [0.1570 0.2400 0.1714 0.2143]
 [0.0897 0.0400 0.0571 0.0714]]


In [94]:
criteriaweights = normalizedform.sum(axis=1)/n
print(criteriaweights)

[0.6034 0.1364 0.1957 0.0646]


In [96]:
#data consistency checling started

i=0
c1 = np.array(mainarr)
for p in mainarr:
    c1[i] = np.multiply(mainarr[i] , criteriaweights)
    i=i+1

print(c1)



[[0.6034 0.6820 0.7827 0.4520]
 [0.1207 0.1364 0.0978 0.1937]
 [0.1508 0.2728 0.1957 0.1937]
 [0.0862 0.0455 0.0652 0.0646]]


In [98]:
weightedsum = c1.sum(axis=1)

#weightedsum upon criteria weight
naipata = np.divide(weightedsum,criteriaweights)
print(naipata)

[4.1764 4.0222 4.1550 4.0494]


In [99]:
lamda = naipata.sum(axis=0)/n

lamda=round(lamda, 4) 
print(lamda)

4.1007


In [100]:
#now we find consistency index CI

CI = (lamda-n)/(n-1)
CI = round(CI,5)
print(CI)


0.03357


In [113]:
#cr is consistency ratio = consistency index upon random index
CR = CI / RI[n-1]

print(CR)


0.0373


In [114]:
if(CR<0.10):
    print("VALUES ARE CONSISTENT - go ahead")
else:
    print("criteria weights are not consistent reEnter the values")
    

VALUES ARE CONSISTENT - go ahead


In [104]:
#function made

def bene(arr) :
    max1 = np.max(arr[1])
    max2 = np.max(arr[2])
    max3 = np.max(arr[3])

    ite=0
    for i in arr[1] :
        arr[1][ite]=i/max1
        ite+=1
    ite=0
    for i in arr[2] :
        arr[2][ite]=i/max2
        ite+=1
    
    ite=0
    for i in arr[3] :
        arr[3][ite]=i/max3
        ite+=1
        
    #non beneficial min/i
    ite=0
    min1 = np.min(arr[0])
    for i in arr[0] :
        arr[0][ite]=min1/i
        ite=ite+1


In [115]:
#Tla transpose list array   ctla copy of tla
listarray = np.array([[250,16,12,5],[200,16,8,3],[300,32,16,4],[275,32,8,4],[225,16,16,2]])
print("\n")
Tla = listarray.T
Tla = Tla.astype('float64') 


# function called
bene(Tla)
Tla = Tla.T
print(Tla)





[[0.8000 0.5000 0.7500 1.0000]
 [1.0000 0.5000 0.5000 0.6000]
 [0.6667 1.0000 1.0000 0.8000]
 [0.7273 1.0000 0.5000 0.8000]
 [0.8889 0.5000 1.0000 0.4000]]


In [120]:
cw = 0
for i in Tla:
    Tla[cw] = np.multiply(Tla[cw],criteriaweights)
    cw+=1
print(Tla)


[[0.4827 0.0682 0.1467 0.0646]
 [0.6034 0.0682 0.0978 0.0387]
 [0.4023 0.1364 0.1957 0.0517]
 [0.4388 0.1364 0.0978 0.0517]
 [0.5363 0.0682 0.1957 0.0258]]


In [125]:
#weighted normalized decision matrix

# out_arr = np.multiply(in_arr1, in_arr2) ye galat hai for what i am doin     

# out_arr=np.array(in_arr1)*np.array(in_arr2) this is right

# wndm = np.array(Tla)*np.array(cw)
# print(wndm)
#now this is according to the other video example


In [121]:
perfscore = Tla.sum(axis=1)
print (perfscore)

[0.7622 0.8081 0.7860 0.7247 0.8260]


In [122]:
rankArr = np.array(perfscore)
ranks = perfscore.size
for score in rankArr :
    rankArr[rankArr.argmin()]=ranks
    ranks-=1
print(rankArr)

[4.0000 2.0000 3.0000 5.0000 1.0000]


In [123]:
finalarr = np.column_stack([listarray,rankArr])
print(finalarr)

[[250.0000 16.0000 12.0000 5.0000 4.0000]
 [200.0000 16.0000 8.0000 3.0000 2.0000]
 [300.0000 32.0000 16.0000 4.0000 3.0000]
 [275.0000 32.0000 8.0000 4.0000 5.0000]
 [225.0000 16.0000 16.0000 2.0000 1.0000]]


In [124]:
finalarr = finalarr[finalarr[:,finalarr[0].size-1].argsort()]
print(finalarr)

[[225.0000 16.0000 16.0000 2.0000 1.0000]
 [200.0000 16.0000 8.0000 3.0000 2.0000]
 [300.0000 32.0000 16.0000 4.0000 3.0000]
 [250.0000 16.0000 12.0000 5.0000 4.0000]
 [275.0000 32.0000 8.0000 4.0000 5.0000]]
