In [1]:
import numpy as np
import pandas as pd
from enum import Enum
RI = np.array([0,0,0.58,0.90,1.12,1.24,1.32,1.41,1.45,1.49,1.51,1.48,1.56,1.57,1.58])

#subcriteria
df =pd.read_csv("WesternGhatData/1Elevation.csv")
elevation= df.to_numpy()

df =pd.read_csv("WesternGhatData/2Slope.csv")
slope= df.to_numpy()

df =pd.read_csv("WesternGhatData/3DistancefromRiver.csv")
river= df.to_numpy()

df =pd.read_csv("WesternGhatData/4Drainage.csv")
drainage= df.to_numpy()

df =pd.read_csv("WesternGhatData/5FlowAccumulation.csv")
flow= df.to_numpy()

df =pd.read_csv("WesternGhatData/6TWI.csv")
twi= df.to_numpy()

df =pd.read_csv("WesternGhatData/7Rainfall.csv")
rainfall= df.to_numpy()

df =pd.read_csv("WesternGhatData/8Landuse.csv")
landuse= df.to_numpy()

df =pd.read_csv("WesternGhatData/9SoilTexture.csv")
soil= df.to_numpy()

df =pd.read_csv("WesternGhatData/10TRI.csv")
tri= df.to_numpy()

df =pd.read_csv("WesternGhatData/11Geology.csv")
geology= df.to_numpy()

# pairwise comparison matrix of main criterias
data = np.array([[1   ,2   ,2   ,3   ,4   ,5   ,5   ,6   ,7   ,8   ,8],
                    [1/2 ,1   ,2   ,3   ,3   ,4   ,5   ,6   ,7   ,8   ,8],
                    [1/2 ,1/2 ,1   ,2   ,3   ,4   ,4   ,5   ,6   ,7   ,7],
                    [1/3 ,1/3 ,1/2 ,1   ,2   ,3   ,3   ,4   ,5   ,7   ,8],
                    [1/4 ,1/3 ,1/3 ,1/2 ,1   ,2   ,2   ,3   ,4   ,5   ,6],
                    [1/5 ,1/4 ,1/4 ,1/3 ,1/2 ,1   ,2   ,4   ,5   ,7   ,7],
                    [1/5 ,1/5 ,1/4 ,1/3 ,1/2 ,1/2 ,1   ,2   ,3   ,5   ,6],
                    [1/6 ,1/6 ,1/5 ,1/4 ,1/3 ,1/4 ,1/2 ,1   ,2   ,4   ,5],
                    [1/7 ,1/7 ,1/6 ,1/5 ,1/4 ,1/5 ,1/3 ,1/2 ,1   ,3   ,4],
                    [1/8 ,1/8 ,1/7 ,1/7 ,1/5 ,1/7 ,1/5 ,1/4 ,1/3 ,1   ,3],
                    [1/8 ,1/8 ,1/7 ,1/8 ,1/6 ,1/7 ,1/6 ,1/5 ,1/4 ,1/3 ,1]]
                   )

# data = np.array([
#                 [1   ,2   ,2   ,3   ,4   ,5   ,5   ,6   ,7   ,8 ],
#                 [1/2 ,1   ,2   ,3   ,3   ,4   ,5   ,6   ,7   ,8 ],
#                 [1/2 ,1/2 ,1   ,2   ,3   ,4   ,4   ,5   ,6   ,7 ],
#                 [1/3 ,1/3 ,1/2 ,1   ,2   ,3   ,3   ,4   ,5   ,7 ],
#                 [1/4 ,1/3 ,1/3 ,1/2 ,1   ,2   ,2   ,3   ,4   ,5 ],
#                 [1/5 ,1/4 ,1/4 ,1/3 ,1/2 ,1   ,2   ,4   ,5   ,7 ],
#                 [1/5 ,1/5 ,1/4 ,1/3 ,1/2 ,1/2 ,1   ,2   ,3   ,5 ],
#                 [1/6 ,1/6 ,1/5 ,1/4 ,1/3 ,1/4 ,1/2 ,1   ,2   ,4 ],
#                 [1/7 ,1/7 ,1/6 ,1/5 ,1/4 ,1/5 ,1/3 ,1/2 ,1   ,3 ],
#                 [1/8 ,1/8 ,1/7 ,1/7 ,1/5 ,1/7 ,1/5 ,1/4 ,1/3 ,1 ]
                
#                  ])

class memfunc(Enum):
    TRIANGULAR = 3
    TRAPEZOIDAL = 4

In [2]:
# change this to change the membership func
size3d=memfunc.TRIANGULAR.value

#converts normal into fuzzyarray
def fuzzify(data):
    n = data[0].size
    mainarr = np.full((n,n,size3d),0,dtype=float)
    for i in range(0,n):
        for j in range(0,n):
            if (data[i][j]>=1):
                mainarr[i][j][0]= data[i][j] if(data[i][j]==1 or data[i][j]==9) else data[i][j]-1
                mainarr[i][j][1]= data[i][j]
                mainarr[i][j][2]= data[i][j] if(data[i][j]==1 or data[i][j]==9) else data[i][j]+1
                if(size3d == memfunc.TRAPEZOIDAL.value):
                    mainarr[i][j][3]= data[i][j]+1 if(data[i][j]==8) else data[i][j] if(data[i][j]==1 or data[i][j]==9) else data[i][j]+2
            else:
                mainarr[i][j]= np.reciprocal(np.flip(mainarr[j][i]))
    return mainarr

In [3]:
# AHP CRITERIA WEIGHTS
def criteriaWeights(mainarr):
    n = mainarr[0].size
    colsum = mainarr.sum(axis=0)
    normalizedform = np.array(mainarr)
    for i in range(0,n):
        normalizedform[i] = np.divide(mainarr[i] , colsum)
    criteriaweights = normalizedform.sum(axis=1)/n
    return criteriaweights
# FUZZY AHP CRITERIA WEIGHTS
def FuzzycriteriaWeights(mainarr):
    n = mainarr[0].size if (np.ndim(mainarr)==2) else int(mainarr[0].size/size3d)
    fuzzyGM = np.full((n,size3d),1,dtype=float)
    for i in range(0,n):
        for j in range(0,n):
            fuzzyGM[i] = np.multiply(fuzzyGM[i],mainarr[i][j])
        fuzzyGM[i]=np.power(fuzzyGM[i],1/n)
    fuzzyWeights=np.full((n,size3d),1,dtype=float)
    for i in range(0,n):
        fuzzyWeights[i]=np.multiply(fuzzyGM[i],np.reciprocal(np.flip(fuzzyGM.sum(axis=0),0)))
    weights = np.average(fuzzyWeights,axis=1)
    weights = np.divide(weights,weights.sum(axis=0))
    return weights

In [4]:
def consistency(mainarr):
    n = int(mainarr[0].size)
    fuzzyArr = fuzzify(mainarr)
    c1 = np.array(mainarr)
    fc1 = np.array(mainarr)
    for i in range(0,n):
        c1[i] = np.multiply(mainarr[i],criteriaWeights((mainarr)))
        fc1[i] = np.multiply(mainarr[i],FuzzycriteriaWeights((mainarr)))
    lamda = np.divide(c1.sum(axis=1),criteriaWeights((mainarr))).sum(axis=0)/n
    flamda = (np.divide((fc1.sum(axis=1)),FuzzycriteriaWeights((mainarr)))).sum(axis=0)/n
    ci = (lamda-n)/(n-1)
    fci = (flamda-n)/(n-1)
    CR = ci / RI[n-1]
    FCR = fci / RI[n-1]

    if(CR<0.1 and FCR<0.1):
        print("CR: ",CR," VALUES ARE CONSISTENT - go ahead")
        print("cwAHP",criteriaWeights(mainarr))
        print("FUZZY CR: ",FCR," VALUES ARE CONSISTENT - go ahead")
        print("cwFuzzyAHP",FuzzycriteriaWeights(fuzzyArr))
    else:
        print("CR: ",CR,"criteria weights are not consistent reEnter the values")
        print("FUZZY CR: ",FCR," VALUES ARE CONSISTENT - go ahead")
    
    return FuzzycriteriaWeights(fuzzyArr)

In [5]:
consistency(data)

CR:  0.05015519741322485  VALUES ARE CONSISTENT - go ahead
cwAHP [0.25041065 0.20424302 0.15864784 0.11215921 0.07729025 0.07231696
 0.04960286 0.03447297 0.0249447  0.01591153]
FUZZY CR:  0.04841149955459437  VALUES ARE CONSISTENT - go ahead
cwFuzzyAHP [0.244717   0.20697732 0.16543225 0.1155813  0.08025604 0.06669517
 0.04988546 0.03278699 0.02342914 0.01423933]


array([0.244717  , 0.20697732, 0.16543225, 0.1155813 , 0.08025604,
       0.06669517, 0.04988546, 0.03278699, 0.02342914, 0.01423933])

In [6]:
print(np.multiply(consistency(elevation),FuzzycriteriaWeights(fuzzify(data))[0]),"Global elevation\n\n")
print(np.multiply(consistency(slope),FuzzycriteriaWeights(fuzzify(data))[1]),"Global slope\n\n")
print(np.multiply(consistency(river),FuzzycriteriaWeights(fuzzify(data))[2]),"Global river\n\n")
print(np.multiply(consistency(drainage),FuzzycriteriaWeights(fuzzify(data))[3]),"Global drainage\n\n")
print(np.multiply(consistency(flow),FuzzycriteriaWeights(fuzzify(data))[4]),"Global flow\n\n")
print(np.multiply(consistency(twi),FuzzycriteriaWeights(fuzzify(data))[5]),"Global twi\n\n")
print(np.multiply(consistency(rainfall),FuzzycriteriaWeights(fuzzify(data))[6]),"Global rainfall\n\n")
print(np.multiply(consistency(landuse),FuzzycriteriaWeights(fuzzify(data))[7]),"Global landuse\n\n")
print(np.multiply(consistency(soil),FuzzycriteriaWeights(fuzzify(data))[8]),"Global soil\n\n")
print(np.multiply(consistency(tri),FuzzycriteriaWeights(fuzzify(data))[9]),"Global tri\n\n")
# print(np.multiply(consistency(geology),FuzzycriteriaWeights(fuzzify(data))[10]),"Global geology\n\n")


CR:  0.02159551613867609  VALUES ARE CONSISTENT - go ahead
cwAHP [0.51810572 0.21808442 0.13925169 0.08397522 0.04058294]
FUZZY CR:  0.021324860097975327  VALUES ARE CONSISTENT - go ahead
cwFuzzyAHP [0.50931485 0.2210592  0.14425756 0.0856766  0.03969178]
[0.124638   0.05409694 0.03530228 0.02096652 0.00971325] Global elevation


CR:  0.029474590206579408  VALUES ARE CONSISTENT - go ahead
cwAHP [0.49854271 0.27594514 0.11266966 0.0698327  0.0430098 ]
FUZZY CR:  0.02932557462709004  VALUES ARE CONSISTENT - go ahead
cwFuzzyAHP [0.49509351 0.27578642 0.114      0.07099814 0.04412193]
[0.10247313 0.05708154 0.02359542 0.014695   0.00913224] Global slope


CR:  0.04215341953280287  VALUES ARE CONSISTENT - go ahead
cwAHP [0.39978196 0.25794431 0.19703637 0.10227381 0.04296354]
FUZZY CR:  0.04156288231905169  VALUES ARE CONSISTENT - go ahead
cwFuzzyAHP [0.3919398  0.2682075  0.19668145 0.1013873  0.04178395]
[0.06483948 0.04437017 0.03253745 0.01677273 0.00691241] Global river


CR:  0.013463