In [1]:
import numpy as np
import pandas as pd
RI = np.array([0,0,0.58,0.90,1.12,1.24,1.32,1.41,1.45,1.49,1.51,1.48,1.56,1.57,1.58])

data = np.array([[1   ,2   ,2   ,3   ,4   ,5   ,5   ,6   ,7   ,8   ,8],
                   [1/2 ,1   ,2   ,3   ,3   ,4   ,5   ,6   ,7   ,8   ,8],
                   [1/2 ,1/2 ,1   ,2   ,3   ,4   ,4   ,5   ,6   ,7   ,7],
                   [1/3 ,1/3 ,1/2 ,1   ,2   ,3   ,3   ,4   ,5   ,7   ,8],
                   [1/4 ,1/3 ,1/3 ,1/2 ,1   ,2   ,2   ,3   ,4   ,5   ,6],
                   [1/5 ,1/4 ,1/4 ,1/3 ,1/2 ,1   ,2   ,4   ,5   ,7   ,7],
                   [1/5 ,1/5 ,1/4 ,1/3 ,1/2 ,1/2 ,1   ,2   ,3   ,5   ,6],
                   [1/6 ,1/6 ,1/5 ,1/4 ,1/3 ,1/4 ,1/2 ,1   ,2   ,4   ,5],
                   [1/7 ,1/7 ,1/6 ,1/5 ,1/4 ,1/5 ,1/3 ,1/2 ,1   ,3   ,4],
                   [1/8 ,1/8 ,1/7 ,1/7 ,1/5 ,1/7 ,1/5 ,1/4 ,1/3 ,1   ,3],
                   [1/8 ,1/8 ,1/7 ,1/8 ,1/6 ,1/7 ,1/6 ,1/5 ,1/4 ,1/3 ,1]]
                  )

n = data[0].size
float_formatter = "{:.3f}".format
np.set_printoptions(formatter={'float_kind':float_formatter})

In [2]:
mainarr = np.full((n,n,3),0,dtype=float)
for i in range(0,n):
    for j in range(0,n):
        if (data[i][j]>=1):
            mainarr[i][j][0]= data[i][j] if(data[i][j]==1 or data[i][j]==9) else data[i][j]-1
            mainarr[i][j][2]= data[i][j] if(data[i][j]==1 or data[i][j]==9) else data[i][j]+1
        else:
            for k in range(2,10):
                if (1/k==data[i][j]):
                    mainarr[i][j][0]= data[i][j] if(data[i][j]==9) else 1/(k+1)
                    mainarr[i][j][2]= data[i][j] if(data[i][j]==9) else 1/(k-1)
        mainarr[i][j][1]= data[i][j]
print(mainarr)

[[[1.000 1.000 1.000]
  [1.000 2.000 3.000]
  [1.000 2.000 3.000]
  [2.000 3.000 4.000]
  [3.000 4.000 5.000]
  [4.000 5.000 6.000]
  [4.000 5.000 6.000]
  [5.000 6.000 7.000]
  [6.000 7.000 8.000]
  [7.000 8.000 9.000]
  [7.000 8.000 9.000]]

 [[0.333 0.500 1.000]
  [1.000 1.000 1.000]
  [1.000 2.000 3.000]
  [2.000 3.000 4.000]
  [2.000 3.000 4.000]
  [3.000 4.000 5.000]
  [4.000 5.000 6.000]
  [5.000 6.000 7.000]
  [6.000 7.000 8.000]
  [7.000 8.000 9.000]
  [7.000 8.000 9.000]]

 [[0.333 0.500 1.000]
  [0.333 0.500 1.000]
  [1.000 1.000 1.000]
  [1.000 2.000 3.000]
  [2.000 3.000 4.000]
  [3.000 4.000 5.000]
  [3.000 4.000 5.000]
  [4.000 5.000 6.000]
  [5.000 6.000 7.000]
  [6.000 7.000 8.000]
  [6.000 7.000 8.000]]

 [[0.250 0.333 0.500]
  [0.250 0.333 0.500]
  [0.333 0.500 1.000]
  [1.000 1.000 1.000]
  [1.000 2.000 3.000]
  [2.000 3.000 4.000]
  [2.000 3.000 4.000]
  [3.000 4.000 5.000]
  [4.000 5.000 6.000]
  [6.000 7.000 8.000]
  [7.000 8.000 9.000]]

 [[0.200 0.250 0.333]
  

In [4]:
#subcriteria
df =pd.read_csv("WesternGhatData/1Elevation.csv")
elevation= df.to_numpy()

df =pd.read_csv("WesternGhatData/2Slope.csv")
slope= df.to_numpy()

df =pd.read_csv("WesternGhatData/3DistancefromRiver.csv")
river= df.to_numpy()

df =pd.read_csv("WesternGhatData/4Drainage.csv")
drainage= df.to_numpy()

df =pd.read_csv("WesternGhatData/5FlowAccumulation.csv")
flow= df.to_numpy()

df =pd.read_csv("WesternGhatData/6TWI.csv")
twi= df.to_numpy()

df =pd.read_csv("WesternGhatData/7Rainfall.csv")
rainfall= df.to_numpy()

df =pd.read_csv("WesternGhatData/8Landuse.csv")
landuse= df.to_numpy()

df =pd.read_csv("WesternGhatData/9SoilTexture.csv")
soil= df.to_numpy()

df =pd.read_csv("WesternGhatData/10TRI.csv")
tri= df.to_numpy()

df =pd.read_csv("WesternGhatData/11Geology.csv")
geology= df.to_numpy()

mainarr = np.array([[1   ,2   ,2   ,3   ,4   ,5   ,5   ,6   ,7   ,8   ,8],
                   [1/2 ,1   ,2   ,3   ,3   ,4   ,5   ,6   ,7   ,8   ,8],
                   [1/2 ,1/2 ,1   ,2   ,3   ,4   ,4   ,5   ,6   ,7   ,7],
                   [1/3 ,1/3 ,1/2 ,1   ,2   ,3   ,3   ,4   ,5   ,7   ,8],
                   [1/4 ,1/3 ,1/3 ,1/2 ,1   ,2   ,2   ,3   ,4   ,5   ,6],
                   [1/5 ,1/4 ,1/4 ,1/3 ,1/2 ,1   ,2   ,4   ,5   ,7   ,7],
                   [1/5 ,1/5 ,1/4 ,1/3 ,1/2 ,1/2 ,1   ,2   ,3   ,5   ,6],
                   [1/6 ,1/6 ,1/5 ,1/4 ,1/3 ,1/4 ,1/2 ,1   ,2   ,4   ,5],
                   [1/7 ,1/7 ,1/6 ,1/5 ,1/4 ,1/5 ,1/3 ,1/2 ,1   ,3   ,4],
                   [1/8 ,1/8 ,1/7 ,1/7 ,1/5 ,1/7 ,1/5 ,1/4 ,1/3 ,1   ,3],
                   [1/8 ,1/8 ,1/7 ,1/8 ,1/6 ,1/7 ,1/6 ,1/5 ,1/4 ,1/3 ,1]]
                  )

n = mainarr[0].size
float_formatter = "{:.3f}".format
np.set_printoptions(formatter={'float_kind':float_formatter})

In [5]:
#converts normal into fuzzyarray
def fuzzify(data):
    n = data[0].size
    mainarr = np.full((n,n,3),0,dtype=float)
    for i in range(0,n):
        for j in range(0,n):
            if (data[i][j]>=1):
                mainarr[i][j][0]= data[i][j] if(data[i][j]==1 or data[i][j]==9) else data[i][j]-1
                mainarr[i][j][2]= data[i][j] if(data[i][j]==1 or data[i][j]==9) else data[i][j]+1
            else:
                for k in range(2,10):
                    if (1/k==data[i][j]):
                        mainarr[i][j][0]= data[i][j] if(data[i][j]==9) else 1/(k+1)
                        mainarr[i][j][2]= data[i][j] if(data[i][j]==9) else 1/(k-1)
            mainarr[i][j][1]= data[i][j]
    return mainarr

In [6]:

def criteriaWeights(mainarr):
    n = int(mainarr[0].size/3)
    # print(n)
    fuzzyGM = np.full((n,3),1,dtype=float)
    for i in range(0,n):
        for j in range(0,n):
            fuzzyGM[i] = np.multiply(fuzzyGM[i],mainarr[i][j])
        fuzzyGM[i]=np.power(fuzzyGM[i],1/n)
    fuzzyWeights=np.full((n,3),1,dtype=float)
    for i in range(0,n):
        fuzzyWeights[i]=np.multiply(fuzzyGM[i],np.reciprocal(np.flip(fuzzyGM.sum(axis=0),0)))
    weights = np.average(fuzzyWeights,axis=1)
    weights = np.divide(weights,weights.sum(axis=0))
    return weights

In [7]:
def consistancy(mainarr):
    #data consistency checking started
    n = mainarr[0].size
    print(n)
    i=0
    c1 = np.array(mainarr)
    for p in mainarr:
        c1[i] = np.multiply(mainarr[i] , criteriaWeights(fuzzify(mainarr)))
        i=i+1


    weightedsum = c1.sum(axis=1)

    #weightedsum upon criteria weight = naipata
    naipata = np.divide(weightedsum,criteriaWeights(fuzzify(mainarr)))
    lamda = naipata.sum(axis=0)/n
    lamda=round(lamda, 4) 
    print("l",lamda)
        #now we find consistency index CI
    CI = (lamda-n)/(n-1)
    CI = round(CI,5)
    #cr is consistency ratio = consistency index upon random index
    CR = CI / RI[n-1]
    print("cr ",CR)
    
    if(CR<0.10):
        print("VALUES ARE CONSISTENT - go ahead")
        return criteriaWeights(fuzzify(mainarr))
    else:
        print("criteria weights are not consistent reEnter the values")


In [8]:
print(consistancy(mainarr))

11
l 11.9359
cr  0.06198013245033113
VALUES ARE CONSISTENT - go ahead
[0.231 0.198 0.160 0.117 0.082 0.070 0.053 0.036 0.026 0.016 0.012]


In [9]:
print(consistancy(elevation),"elevation\n\n")
print(consistancy(slope),"slope\n\n")
print(consistancy(river),"river\n\n")
print(consistancy(drainage),"drainage\n\n")
print(consistancy(flow),"flow\n\n")
print(consistancy(twi),"twi\n\n")
print(consistancy(rainfall),"rainfall\n\n")
print(consistancy(landuse),"landuse\n\n")
print(consistancy(soil),"soil\n\n")
print(consistancy(tri),"tri\n\n")
print(consistancy(geology),"geology\n\n")

5
l 8.2537
cr  0.7262678571428571
criteria weights are not consistent reEnter the values
None elevation


5
l 8.0002
cr  0.6696874999999999
criteria weights are not consistent reEnter the values
None slope


5
l 8.6659
cr  0.8182857142857142
criteria weights are not consistent reEnter the values
None river


5
l 8.2228
cr  0.7193749999999999
criteria weights are not consistent reEnter the values
None drainage


5
l 7.7441
cr  0.6125267857142856
criteria weights are not consistent reEnter the values
None flow


5
l 8.5212
cr  0.7859821428571427
criteria weights are not consistent reEnter the values
None twi


5
l 8.3814
cr  0.7547767857142856
criteria weights are not consistent reEnter the values
None rainfall


6
l 10.0851
cr  0.6588870967741935
criteria weights are not consistent reEnter the values
None landuse


7
l 11.8271
cr  0.6094848484848485
criteria weights are not consistent reEnter the values
None soil


5
l 8.3481
cr  0.7473482142857143
criteria weights are not consistent re

In [7]:
#function made
def bene(arr):
    num=0
    while num<n:
        ite=0
        max=np.max(arr[num])
        min=np.min(arr[num])
        for i in arr[num] :
            if(num != 0):
                arr[num][ite]=i/max
            else:
                arr[num][ite]=min/i
            ite+=1
        num+=1

In [12]:
#Tla transpose list array   ctla copy of tla
listarray = np.array([[250,16,12,5],[200,16,8,3],[300,32,16,4],[275,32,8,4],[225,16,16,2]])
print("\n")
Tla = listarray.T
Tla = Tla.astype('float64') 

# function called
bene(Tla)
Tla = Tla.T
print(Tla)



IndexError: index 4 is out of bounds for axis 0 with size 4

In [ ]:
cw = 0
for i in Tla:
    Tla[cw] = np.multiply(Tla[cw],criteriaweights)
    cw+=1
print(Tla)


In [ ]:
#weighted normalized decision matrix

# out_arr = np.multiply(in_arr1, in_arr2) ye galat hai for what i am doin     

# out_arr=np.array(in_arr1)*np.array(in_arr2) this is right

# wndm = np.array(Tla)*np.array(cw)
# print(wndm)
#now this is according to the other video example


In [ ]:
perfscore = Tla.sum(axis=1)
print (perfscore)

In [ ]:
rankArr = np.array(perfscore)
ranks = perfscore.size
for score in rankArr :
    rankArr[rankArr.argmin()]=ranks
    ranks-=1
print(rankArr)

In [ ]:
finalarr = np.column_stack([listarray,rankArr])
print(finalarr)

In [ ]:
finalarr = finalarr[finalarr[:,finalarr[0].size-1].argsort()]
print(finalarr)