In [16]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import plotly.express as px
RI = np.array([0,0,0.58,0.90,1.12,1.24,1.32,1.41,1.45,1.49,1.51,1.48,1.56,1.57,1.58])

mainarr = np.array([[1   ,2   ,2   ,3   ,4   ,5   ,5   ,6   ,7   ,8   ,8],
                   [1/2 ,1   ,2   ,3   ,3   ,4   ,5   ,6   ,7   ,8   ,8],
                   [1/2 ,1/2 ,1   ,2   ,3   ,4   ,4   ,5   ,6   ,7   ,7],
                   [1/3 ,1/3 ,1/2 ,1   ,2   ,3   ,3   ,4   ,5   ,7   ,8],
                   [1/4 ,1/3 ,1/3 ,1/2 ,1   ,2   ,2   ,3   ,4   ,5   ,6],
                   [1/5 ,1/4 ,1/4 ,1/3 ,1/2 ,1   ,2   ,4   ,5   ,7   ,7],
                   [1/5 ,1/5 ,1/4 ,1/3 ,1/2 ,1/2 ,1   ,2   ,3   ,5   ,6],
                   [1/6 ,1/6 ,1/5 ,1/4 ,1/3 ,1/4 ,1/2 ,1   ,2   ,4   ,5],
                   [1/7 ,1/7 ,1/6 ,1/5 ,1/4 ,1/5 ,1/3 ,1/2 ,1   ,3   ,4],
                   [1/8 ,1/8 ,1/7 ,1/7 ,1/5 ,1/7 ,1/5 ,1/4 ,1/3 ,1   ,3],
                   [1/8 ,1/8 ,1/7 ,1/8 ,1/6 ,1/7 ,1/6 ,1/5 ,1/4 ,1/3 ,1]]
                  )


# Sample data for demonstration
data = pd.DataFrame([[1, 2, 2, 3, 4, 5, 5, 6, 7, 8, 8],
                     [1/2, 1, 2, 3, 3, 4, 5, 6, 7, 8, 8],
                     [1/2, 1/2, 1, 2, 3, 4, 4, 5, 6, 7, 7],
                     [1/3, 1/3, 1/2, 1, 2, 3, 3, 4, 5, 7, 8],
                     [1/4, 1/3, 1/3, 1/2, 1, 2, 2, 3, 4, 5, 6],
                     [1/5, 1/4, 1/4, 1/3, 1/2, 1, 2, 4, 5, 7, 7],
                     [1/5, 1/5, 1/4, 1/3, 1/2, 1/2, 1, 2, 3, 5, 6],
                     [1/6, 1/6, 1/5, 1/4, 1/3, 1/4, 1/2, 1, 2, 4, 5],
                     [1/7, 1/7, 1/6, 1/5, 1/4, 1/5, 1/3, 1/2, 1, 3, 4],
                     [1/8, 1/8, 1/7, 1/7, 1/5, 1/7, 1/5, 1/4, 1/3, 1, 3],
                     [1/8, 1/8, 1/7, 1/8, 1/6, 1/7, 1/6, 1/5, 1/4, 1/3, 1]])

# Standardize the data
scaler = StandardScaler()
data_scaled = scaler.fit_transform(mainarr)

# Perform PCA
pca = PCA()  # Adjust number of components as needed
principal_components = pca.fit_transform(data_scaled)

# Create a DataFrame with the principal components
pc_df = pd.DataFrame(data=principal_components, columns=['PC1', 'PC2', 'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'PC8', 'PC9', 'PC10', 'PC11'])

# Explained variance
explained_variance = pca.explained_variance_ratio_

# Output results
print("Principal Components:\n", pc_df)
print("Explained Variance:\n", explained_variance)

for i in range(0,mainarr[0].size):
    mainarr[i] = np.multiply(mainarr[i],explained_variance)
print("test\n",mainarr.round(4))


n = mainarr[0].size
# float_formatter = "{:.3f}".format
# np.set_printoptions(formatter={'float_kind':float_formatter})

Principal Components:
          PC1       PC2       PC3       PC4       PC5       PC6       PC7  \
0   5.955599 -1.610213  0.883354 -0.153376 -0.057685  0.001574 -0.002905   
1   4.431454 -0.087854 -0.750800  0.819901  0.067486 -0.075210  0.014356   
2   2.760967  0.278819 -0.732507 -0.551815  0.015428  0.225583 -0.038764   
3   1.233078  1.174735 -0.109612 -0.499891  0.249220 -0.132924  0.025194   
4  -0.419574  0.561250  0.024690 -0.261386 -0.200804 -0.234547  0.059902   
5  -0.280933  1.638931  0.384315  0.258440 -0.482827  0.057538 -0.028654   
6  -1.468185  0.662546  0.391361  0.201716  0.141799  0.092972 -0.071074   
7  -2.253204  0.165925  0.323715  0.188131  0.263822  0.110765  0.041463   
8  -2.817734 -0.323170  0.146190  0.110344  0.263128  0.060864  0.093380   
9  -3.389953 -0.939520 -0.125689 -0.017877  0.124395 -0.164964 -0.137156   
10 -3.751515 -1.521448 -0.435017 -0.094187 -0.383963  0.058349  0.044258   

         PC8       PC9      PC10          PC11  
0  -0.006908  0

In [9]:
criteriaweights = []  
def criteriaWeights(mainarr):
    n = mainarr[0].size
    colsum = mainarr.sum(axis=0)
    # normalized form 
    i=0
    
    normalizedform = np.array(mainarr)
    for p in mainarr:
        normalizedform[i] = np.divide(mainarr[i] , colsum)
        i+=1
    
    # finding criteriaweights
    criteriaweights = normalizedform.sum(axis=1)/n

    #data consistency checking started

    i=0
    c1 = np.array(mainarr)
    for p in mainarr:
        c1[i] = np.multiply(mainarr[i] , criteriaweights)
        i=i+1

    weightedsum = c1.sum(axis=1)

    #weightedsum upon criteria weight = naipata
    naipata = np.divide(weightedsum,criteriaweights)
    lamda = naipata.sum(axis=0)/n
    lamda=round(lamda, 4) 
        #now we find consistency index CI
    CI = (lamda-n)/(n-1)
    CI = round(CI,5)
    #cr is consistency ratio = consistency index upon random index
    CR = CI / RI[n-1]
    print("cr ",CR)
    
    if(CR<0.10):
        print("VALUES ARE CONSISTENT - go ahead")
        return criteriaweights
    else:
        print("criteria weights are not consistent reEnter the values")



In [10]:
#subcriteria
df =pd.read_csv("WesternGhatData/1Elevation.csv")
elevation= df.to_numpy()

df =pd.read_csv("WesternGhatData/2Slope.csv")
slope= df.to_numpy()

df =pd.read_csv("WesternGhatData/3DistancefromRiver.csv")
river= df.to_numpy()

df =pd.read_csv("WesternGhatData/4Drainage.csv")
drainage= df.to_numpy()

df =pd.read_csv("WesternGhatData/5FlowAccumulation.csv")
flow= df.to_numpy()

df =pd.read_csv("WesternGhatData/6TWI.csv")
twi= df.to_numpy()

df =pd.read_csv("WesternGhatData/7Rainfall.csv")
rainfall= df.to_numpy()

df =pd.read_csv("WesternGhatData/8Landuse.csv")
landuse= df.to_numpy()

df =pd.read_csv("WesternGhatData/9SoilTexture.csv")
soil= df.to_numpy()

df =pd.read_csv("WesternGhatData/10TRI.csv")
tri= df.to_numpy()

df =pd.read_csv("WesternGhatData/11Geology.csv")
geology= df.to_numpy()

In [11]:
print(criteriaWeights(mainarr))

cr  -0.6606158940397351
VALUES ARE CONSISTENT - go ahead
[0.236 0.195 0.152 0.112 0.078 0.075 0.053 0.038 0.028 0.019 0.014]


In [12]:
print(criteriaWeights(elevation),"elevation\n\n")
print(criteriaWeights(slope),"slope\n\n")
print(criteriaWeights(river),"river\n\n")
print(criteriaWeights(drainage),"drainage\n\n")
print(criteriaWeights(flow),"flow\n\n")
print(criteriaWeights(twi),"twi\n\n")
print(criteriaWeights(rainfall),"rainfall\n\n")
print(criteriaWeights(landuse),"landuse\n\n")
print(criteriaWeights(soil),"soil\n\n")
print(criteriaWeights(tri),"tri\n\n")
print(criteriaWeights(geology),"geology\n\n")

cr  0.021589285714285714
VALUES ARE CONSISTENT - go ahead
[0.518 0.218 0.139 0.084 0.041] elevation


cr  0.029464285714285714
VALUES ARE CONSISTENT - go ahead
[0.499 0.276 0.113 0.070 0.043] slope


cr  0.042142857142857135
VALUES ARE CONSISTENT - go ahead
[0.400 0.258 0.197 0.102 0.043] river


cr  0.013455357142857142
VALUES ARE CONSISTENT - go ahead
[0.433 0.262 0.164 0.089 0.052] drainage


cr  0.01138392857142857
VALUES ARE CONSISTENT - go ahead
[0.423 0.287 0.151 0.088 0.050] flow


cr  0.04176785714285714
VALUES ARE CONSISTENT - go ahead
[0.421 0.253 0.192 0.090 0.045] twi


cr  0.015241071428571425
VALUES ARE CONSISTENT - go ahead
[0.416 0.262 0.161 0.099 0.062] rainfall


cr  0.01987096774193548
VALUES ARE CONSISTENT - go ahead
[0.379 0.249 0.160 0.102 0.065 0.043] landuse


cr  0.02862121212121212
VALUES ARE CONSISTENT - go ahead
[0.331 0.231 0.152 0.123 0.081 0.050 0.033] soil


cr  0.059125
VALUES ARE CONSISTENT - go ahead
[0.398 0.300 0.171 0.093 0.037] tri


cr  0.007931

In [13]:
#function made
def bene(arr):
    num=0
    while num<n:
        ite=0
        max=np.max(arr[num])
        min=np.min(arr[num])
        for i in arr[num] :
            if(num != 0):
                arr[num][ite]=i/max
            else:
                arr[num][ite]=min/i
            ite+=1
        num+=1

In [14]:
#Tla transpose list array   ctla copy of tla
listarray = np.array([[250,16,12,5],[200,16,8,3],[300,32,16,4],[275,32,8,4],[225,16,16,2]])
print("\n")
Tla = listarray.T
Tla = Tla.astype('float64') 

# function called
bene(Tla)
Tla = Tla.T
print(Tla)



IndexError: index 4 is out of bounds for axis 0 with size 4

In [ ]:
cw = 0
for i in Tla:
    Tla[cw] = np.multiply(Tla[cw],criteriaweights)
    cw+=1
print(Tla)


In [ ]:
#weighted normalized decision matrix

# out_arr = np.multiply(in_arr1, in_arr2) ye galat hai for what i am doin     

# out_arr=np.array(in_arr1)*np.array(in_arr2) this is right

# wndm = np.array(Tla)*np.array(cw)
# print(wndm)
#now this is according to the other video example


In [ ]:
perfscore = Tla.sum(axis=1)
print (perfscore)

In [ ]:
rankArr = np.array(perfscore)
ranks = perfscore.size
for score in rankArr :
    rankArr[rankArr.argmin()]=ranks
    ranks-=1
print(rankArr)

In [ ]:
finalarr = np.column_stack([listarray,rankArr])
print(finalarr)

In [ ]:
finalarr = finalarr[finalarr[:,finalarr[0].size-1].argsort()]
print(finalarr)