In [23]:
import numpy as np
RI = np.array([0,0,0.58,0.90,1.12,1.24,1.32,1.41,1.45,1.49,1.51,1.48,1.56,1.57,1.58])

mainarr = np.array([[1   ,2   ,2   ,3   ,4   ,5   ,5   ,6   ,7   ,8   ,8],
                   [1/2 ,1   ,2   ,3   ,3   ,4   ,5   ,6   ,7   ,8   ,8],
                   [1/2 ,1/2 ,1   ,2   ,3   ,4   ,4   ,5   ,6   ,7   ,7],
                   [1/3 ,1/3 ,1/2 ,1   ,2   ,3   ,3   ,4   ,5   ,7   ,8],
                   [1/4 ,1/3 ,1/3 ,1/2 ,1   ,2   ,2   ,3   ,4   ,5   ,6],
                   [1/5 ,1/4 ,1/4 ,1/3 ,1/2 ,1   ,2   ,4   ,5   ,7   ,7],
                   [1/5 ,1/5 ,1/4 ,1/3 ,1/2 ,1/2 ,1   ,2   ,3   ,5   ,6],
                   [1/6 ,1/6 ,1/5 ,1/4 ,1/3 ,1/4 ,1/2 ,1   ,2   ,4   ,5],
                   [1/7 ,1/7 ,1/6 ,1/5 ,1/4 ,1/5 ,1/3 ,1/2 ,1   ,3   ,4],
                   [1/8 ,1/8 ,1/7 ,1/7 ,1/5 ,1/7 ,1/5 ,1/4 ,1/3 ,1   ,3],
                   [1/8 ,1/8 ,1/7 ,1/8 ,1/6 ,1/7 ,1/6 ,1/5 ,1/4 ,1/3 ,1]]
                  )

n = mainarr[0].size
float_formatter = "{:.4f}".format
np.set_printoptions(formatter={'float_kind':float_formatter})

In [24]:
def criteriaWeights(mainarr):
    n = mainarr[0].size
    colsum = mainarr.sum(axis=0)
    # normalized form 
    i=0
    
    normalizedform = np.array(mainarr)
    for p in mainarr:
        normalizedform[i] = np.divide(mainarr[i] , colsum)
        i+=1
    
    # finding criteriaweights
    criteriaweights = normalizedform.sum(axis=1)/n

    #data consistency checling started

    i=0
    c1 = np.array(mainarr)
    for p in mainarr:
        c1[i] = np.multiply(mainarr[i] , criteriaweights)
        i=i+1

    weightedsum = c1.sum(axis=1)

    #weightedsum upon criteria weight = naipata
    naipata = np.divide(weightedsum,criteriaweights)
    lamda = naipata.sum(axis=0)/n
    lamda=round(lamda, 4) 
        #now we find consistency index CI
    CI = (lamda-n)/(n-1)
    CI = round(CI,5)

    #cr is consistency ratio = consistency index upon random index
    CR = CI / RI[n-1]
    print("cr ",CR)
    
    if(CR<0.10):
        print("VALUES ARE CONSISTENT - go ahead")
        return criteriaweights
    else:
        print("criteria weights are not consistent reEnter the values")



In [10]:
#subcriteria


In [20]:
print(criteriaWeights(mainarr))

cr  0.06480132450331126
VALUES ARE CONSISTENT - go ahead
[0.2357 0.1947 0.1525 0.1123 0.0781 0.0751 0.0532 0.0381 0.0281 0.0185
 0.0137]


In [25]:
#function made
def bene(arr):
    num=0
    while num<n:
        ite=0
        max=np.max(arr[num])
        min=np.min(arr[num])
        for i in arr[num] :
            if(num != 0):
                arr[num][ite]=i/max
            else:
                arr[num][ite]=min/i
            ite+=1
        num+=1

In [13]:
#Tla transpose list array   ctla copy of tla
listarray = np.array([[250,16,12,5],[200,16,8,3],[300,32,16,4],[275,32,8,4],[225,16,16,2]])
print("\n")
Tla = listarray.T
Tla = Tla.astype('float64') 


# function called
bene(Tla)
Tla = Tla.T
print(Tla)





[[0.8000 0.5000 0.7500 1.0000]
 [1.0000 0.5000 0.5000 0.6000]
 [0.6667 1.0000 1.0000 0.8000]
 [0.7273 1.0000 0.5000 0.8000]
 [0.8889 0.5000 1.0000 0.4000]]


In [19]:
cw = 0
for i in Tla:
    Tla[cw] = np.multiply(Tla[cw],criteriaweights)
    cw+=1
print(Tla)


NameError: name 'criteriaweights' is not defined

In [ ]:
#weighted normalized decision matrix

# out_arr = np.multiply(in_arr1, in_arr2) ye galat hai for what i am doin     

# out_arr=np.array(in_arr1)*np.array(in_arr2) this is right

# wndm = np.array(Tla)*np.array(cw)
# print(wndm)
#now this is according to the other video example


In [ ]:
perfscore = Tla.sum(axis=1)
print (perfscore)

In [ ]:
rankArr = np.array(perfscore)
ranks = perfscore.size
for score in rankArr :
    rankArr[rankArr.argmin()]=ranks
    ranks-=1
print(rankArr)

In [ ]:
finalarr = np.column_stack([listarray,rankArr])
print(finalarr)

In [ ]:
finalarr = finalarr[finalarr[:,finalarr[0].size-1].argsort()]
print(finalarr)